version: '3.8'

services:
  database:
    image: postgres:16
    container_name: mobai-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: 123456    
      POSTGRES_DB: mobai_db    
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: